# Generated by Django 6.0 on 2026-02-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='age',
        ),
    ]
