# Generated by Django 6.0 on 2026-02-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_resident_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skmember',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='skmember',
            name='role',
            field=models.CharField(choices=[('chairman', 'SK Chairman'), ('secretary', 'SK Secretary'), ('treasurer', 'SK Treasurer'), ('education', 'SK Kagawad – Education'), ('health', 'SK Kagawad – Health'), ('sports', 'SK Kagawad – Sports'), ('social', 'SK Kagawad – Social Inclusion'), ('livelihood', 'SK Kagawad – Livelihood'), ('environment', 'SK Kagawad – Environment')], max_length=50, unique=True),
        ),
    ]
