# Generated by Django 6.0.2 on 2026-02-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_skmember_options_alter_skmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skmember',
            name='role',
            field=models.CharField(choices=[('chairman', 'SK Chairman'), ('secretary', 'SK Secretary'), ('treasurer', 'SK Treasurer'), ('appro', 'SK Kagawad – Appro'), ('education', 'SK Kagawad – Education'), ('health', 'SK Kagawad – Health'), ('sports', 'SK Kagawad – Sports'), ('social', 'SK Kagawad – Social Inclusion'), ('livelihood', 'SK Kagawad – Livelihood'), ('environment', 'SK Kagawad – Environment')], max_length=50, unique=True),
        ),
    ]
